version: '3.8'

services:
  mySQL:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock

    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


  java-app:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mySQL
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mySQL:3307/stock
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root


volumes:
  db_data:
